/*
 * This source file was generated by the Gradle 'init' task
 */
package org.nithish.vehiclesim;

import org.nithish.vehiclesim.engine.GameLoop;

public class App {

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        new GameLoop().run();
    }
}
